/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>


#include "interface.h"
#include "callback.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget* create_window2 (void){
  GtkWidget *window2;
  GtkWidget *fixed1;
  GtkWidget *label2;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label7;
  GtkWidget *label1;
  GtkWidget *label13;
  GtkWidget *checkbutton13;
  GtkWidget *checkbutton0;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *checkbutton17;
  GtkWidget *checkbutton16;
  GtkWidget *checkbutton15;
  GtkWidget *checkbutton14;
  GtkWidget *checkbutton12;
  GtkWidget *checkbutton11;
  GtkWidget *checkbutton10;
  GtkWidget *label25;
  GtkWidget *checkbutton20;
  GtkWidget *checkbutton22;
  GtkWidget *checkbutton23;
  GtkWidget *checkbutton24;
  GtkWidget *checkbutton25;
  GtkWidget *checkbutton26;
  GtkWidget *checkbutton27;
  GtkWidget *checkbutton21;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *hscale18;
  GtkWidget *label28;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *checkbutton55;
  GtkWidget *checkbutton56;
  GtkWidget *checkbutton54;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *label31;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *label29;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton3;
  GtkWidget *label30;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *hscale29;
  GtkWidget *hscale30;
  GtkWidget *hseparator3;
  GtkWidget *label34;
  GtkWidget *checkbutton57;
  GtkWidget *checkbutton58;
  GtkWidget *checkbutton60;
  GtkWidget *checkbutton59;
  GtkWidget *hscale31;
  GtkWidget *label35;
  GtkWidget *radiobutton9;
  GSList *radiobutton9_group = NULL;
  GtkWidget *radiobutton10;
  GtkWidget *hseparator2;
  GtkWidget *hscale32;
  GtkWidget *label36;
  GtkWidget *hscale1;
  GtkWidget *hscale2;
  GtkWidget *hscale3;
  GtkWidget *hscale4;
  GtkWidget *hscale5;
  GtkWidget *hscale6;
  GtkWidget *hscale7;
  GtkWidget *hscale0;
  GtkWidget *hscale11;
  GtkWidget *hscale17;
  GtkWidget *hscale16;
  GtkWidget *hscale12;
  GtkWidget *hscale13;
  GtkWidget *hscale15;
  GtkWidget *hscale14;
  GtkWidget *hscale10;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button3;

  GtkWidget *hseparator1;
  GtkWidget *label37;
  GtkWidget *checkbutton61;
  GtkWidget *checkbutton62;
  GtkWidget *checkbutton63;
  GtkWidget *checkbutton64;
  GtkWidget *checkbutton65;
  GtkWidget *checkbutton66;
  GtkWidget *checkbutton67;
  GtkWidget *checkbutton68;
  GtkWidget *hscale33;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *hscale34;
  GtkWidget *label40;
  GtkWidget *hscale35;

  GtkWidget *label41;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *radiobutton12;


  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), ("V1720 Configuration"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window2), fixed1);

  label2 = gtk_label_new (("Ch 0"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 0, 64);
  gtk_widget_set_size_request (label2, 64, 24);

  label10 = gtk_label_new (("Enabled"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 72, 32);
  gtk_widget_set_size_request (label10, 64, 32);

  label11 = gtk_label_new (("Internal Trigger \nEnable"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 136, 24);
  gtk_widget_set_size_request (label11, 168, 40);

  label12 = gtk_label_new (("Internal trigger thr (mV)"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 296, 16);
  gtk_widget_set_size_request (label12, 152, 40);
 
  label3 = gtk_label_new (("Ch 1"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 104);
  gtk_widget_set_size_request (label3, 64, 24);

  label4 = gtk_label_new (("Ch 2"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 0, 144);
  gtk_widget_set_size_request (label4, 64, 24);

  label5 = gtk_label_new (("Ch 3"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 0, 184);
  gtk_widget_set_size_request (label5, 64, 24);

  label6 = gtk_label_new (("Ch 4"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 0, 224);
  gtk_widget_set_size_request (label6, 64, 24);

  label8 = gtk_label_new (("Ch 5"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 0, 264);
  gtk_widget_set_size_request (label8, 64, 24);

  label9 = gtk_label_new (("Ch 6"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 0, 304);
  gtk_widget_set_size_request (label9, 64, 24);

  label7 = gtk_label_new (("Ch 7"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 0, 344);
  gtk_widget_set_size_request (label7, 64, 24);

  label1 = gtk_label_new (("Single Channels Configuration"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 0);
  gtk_widget_set_size_request (label1, 208, 32);

  label13 = gtk_label_new (("Propagate\ntrigger ext."));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 504, 16);
  gtk_widget_set_size_request (label13, 96, 40);

  checkbutton13 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton13);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton13, 176, 184);
  gtk_widget_set_size_request (checkbutton13, 16, 16);

  checkbutton0 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton0);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton0, 80, 64);
  gtk_widget_set_size_request (checkbutton0, 16, 16);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 80, 104);
  gtk_widget_set_size_request (checkbutton1, 16, 16);

  checkbutton2 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton2, 80, 144);
  gtk_widget_set_size_request (checkbutton2, 24, 16);

  checkbutton3 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton3, 80, 184);
  gtk_widget_set_size_request (checkbutton3, 24, 16);

  checkbutton4 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton4, 80, 224);
  gtk_widget_set_size_request (checkbutton4, 24, 16);

  checkbutton5 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton5, 80, 264);
  gtk_widget_set_size_request (checkbutton5, 24, 16);

  checkbutton6 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton6, 80, 304);
  gtk_widget_set_size_request (checkbutton6, 16, 16);

  checkbutton7 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton7);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton7, 80, 344);
  gtk_widget_set_size_request (checkbutton7, 24, 16);

  checkbutton17 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton17);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton17, 176, 344);
  gtk_widget_set_size_request (checkbutton17, 16, 16);

  checkbutton16 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton16);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton16, 176, 304);
  gtk_widget_set_size_request (checkbutton16, 24, 16);

  checkbutton15 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton15);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton15, 176, 264);
  gtk_widget_set_size_request (checkbutton15, 24, 16);

  checkbutton14 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton14);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton14, 176, 224);
  gtk_widget_set_size_request (checkbutton14, 24, 16);

  checkbutton12 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton12);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton12, 176, 144);
  gtk_widget_set_size_request (checkbutton12, 24, 16);

  checkbutton11 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton11);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton11, 176, 104);
  gtk_widget_set_size_request (checkbutton11, 24, 16);

  checkbutton10 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton10);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton10, 176, 64);
  gtk_widget_set_size_request (checkbutton10, 24, 16);

  label25 = gtk_label_new (("DAC Value (mV) \n 0: negative unipolar"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed1), label25, 632, 24);
  gtk_widget_set_size_request (label25, 212, 31);

  checkbutton20 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton20);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton20, 536, 64);
  gtk_widget_set_size_request (checkbutton20, 24, 16);

  checkbutton22 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton22);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton22, 536, 144);
  gtk_widget_set_size_request (checkbutton22, 24, 16);

  checkbutton23 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton23);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton23, 536, 184);
  gtk_widget_set_size_request (checkbutton23, 24, 16);

  checkbutton24 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton24);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton24, 536, 224);
  gtk_widget_set_size_request (checkbutton24, 24, 16);

  checkbutton25 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton25);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton25, 536, 264);
  gtk_widget_set_size_request (checkbutton25, 16, 16);

  checkbutton26 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton26);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton26, 536, 304);
  gtk_widget_set_size_request (checkbutton26, 24, 16);

  checkbutton27 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton27);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton27, 536, 344);
  gtk_widget_set_size_request (checkbutton27, 16, 16);

  checkbutton21 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton21);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton21, 536, 104);
  gtk_widget_set_size_request (checkbutton21, 24, 16);

  label26 = gtk_label_new (("Board configuration"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed1), label26, 0, 392);
  gtk_widget_set_size_request (label26, 168, 24);

  label27 = gtk_label_new (("Number of Samples\n per event and channel"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed1), label27, 8, 424);
  gtk_widget_set_size_request (label27, 152, 40);


  hscale18= gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 8, 1024, 1, 0, 0)));
  gtk_widget_show (hscale18);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale18, 200, 430);
  gtk_widget_set_size_request (hscale18, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale18), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale18), 0);


   label28 = gtk_label_new ("");
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed1), label28, 472, 440);
  gtk_widget_set_size_request (label28, 46, 17);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 400, 392);
  gtk_widget_set_size_request (vseparator1, 16, 152);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator2, 624, 392);
  gtk_widget_set_size_request (vseparator2, 16, 152);

  checkbutton55 = gtk_check_button_new_with_mnemonic (("BERR Enable (expert)"));
  gtk_widget_show (checkbutton55);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton55, 8, 480);
  gtk_widget_set_size_request (checkbutton55, 192, 16);

  checkbutton56 = gtk_check_button_new_with_mnemonic (("ALIGN64 Enable (expert)"));
  gtk_widget_show (checkbutton56);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton56, 8, 504);
  gtk_widget_set_size_request (checkbutton56, 184, 16);

  checkbutton54 = gtk_check_button_new_with_mnemonic (("Enable Interrupt on\nOptical Link"));
  gtk_widget_show (checkbutton54);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton54, 16, 576);
  gtk_widget_set_size_request (checkbutton54, 144, 48);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, ("Interrupt reg acc. RORA"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton7, 176, 584);
  gtk_widget_set_size_request (radiobutton7, 176, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, ("Interrupt ack. ROAK"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton8, 176, 608);
  gtk_widget_set_size_request (radiobutton8, 164, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  label31 = gtk_label_new (("Interrupt Control"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed1), label31, 8, 552);
  gtk_widget_set_size_request (label31, 128, 16);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, ("Count accepted triggers"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 440, 480);
  gtk_widget_set_size_request (radiobutton2, 184, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, ("Count all triggers"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 440, 448);
  gtk_widget_set_size_request (radiobutton1, 176, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label29 = gtk_label_new (("Trigger count"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed1), label29, 440, 408);
  gtk_widget_set_size_request (label29, 96, 17);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, ("S-In Controlled"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton4, 648, 480);
  gtk_widget_set_size_request (radiobutton4, 144, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, ("MultyBoard"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton6, 824, 480);
  gtk_widget_set_size_request (radiobutton6, 104, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, ("S-IN gate"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton5, 824, 448);
  gtk_widget_set_size_request (radiobutton5, 104, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, ("Register-Controlled "));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton3, 648, 448);
  gtk_widget_set_size_request (radiobutton3, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  

  label30 = gtk_label_new (("Acquisition Mode (expert)"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed1), label30, 640, 408);
  gtk_widget_set_size_request (label30, 184, 16);

  label32 = gtk_label_new (("BLT Event Number"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed1), label32, 248, 472);
  gtk_widget_set_size_request (label32, 144, 16);

  label33 = gtk_label_new (("Interrupt event \nnumber"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed1), label33, 408, 560);
  gtk_widget_set_size_request (label33, 128, 40);

  hscale29 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 1, 255, 1, 0, 0)));
  gtk_widget_show (hscale29);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale29, 256, 488);
  gtk_widget_set_size_request (hscale29, 120, 46);
  gtk_scale_set_digits (GTK_SCALE (hscale29), 0);

  hscale30 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 10, 1, 0, 0)));
  gtk_widget_show (hscale30);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale30, 416, 592);
  gtk_widget_set_size_request (hscale30, 144, 46);
  gtk_scale_set_digits (GTK_SCALE (hscale30), 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator3, 0, 672);
  gtk_widget_set_size_request (hseparator3, 1008, 16);

  label34 = gtk_label_new (("Trigger Control"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed1), label34, 8, 688);
  gtk_widget_set_size_request (label34, 120, 16);

  checkbutton57 = gtk_check_button_new_with_mnemonic (("Ext trigger enable"));
  gtk_widget_show (checkbutton57);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton57, 24, 712);
  gtk_widget_set_size_request (checkbutton57, 152, 24);

  checkbutton58 = gtk_check_button_new_with_mnemonic (("Software trigger enable"));
  gtk_widget_show (checkbutton58);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton58, 24, 744);
  gtk_widget_set_size_request (checkbutton58, 184, 16);

  checkbutton60 = gtk_check_button_new_with_mnemonic (("Software trigger out enable"));
  gtk_widget_show (checkbutton60);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton60, 224, 744);
  gtk_widget_set_size_request (checkbutton60, 208, 16);

  checkbutton59 = gtk_check_button_new_with_mnemonic (("Ext trigger out enable"));
  gtk_widget_show (checkbutton59);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton59, 224, 712);
  gtk_widget_set_size_request (checkbutton59, 176, 24);

  hscale31 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1000, 1, 0, 0)));
  gtk_widget_show (hscale31);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale31, 496, 712);
  gtk_widget_set_size_request (hscale31, 160, 32);
  gtk_scale_set_digits (GTK_SCALE (hscale31), 0);

  label35 = gtk_label_new (("Post trigger samples"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed1), label35, 488, 688);
  gtk_widget_set_size_request (label35, 160, 16);

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, ("Internal trigger negative polarity"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton9, 32, 776);
  gtk_widget_set_size_request (radiobutton9, 232, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, ("Internal trigger positive polarity"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton10, 32, 800);
  gtk_widget_set_size_request (radiobutton10, 232, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator2, 0, 528);
  gtk_widget_set_size_request (hseparator2, 1008, 32);

  hscale32 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 7, 1, 0, 0)));
  gtk_widget_show (hscale32);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale32, 632, 600);
  gtk_widget_set_size_request (hscale32, 152, 32);
  gtk_scale_set_digits (GTK_SCALE (hscale32), 0);

  label36 = gtk_label_new (("Interrupt Level (0:disabled)"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed1), label36, 624, 576);
  gtk_widget_set_size_request (label36, 184, 16);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale1);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale1, 296, 96);
  gtk_widget_set_size_request (hscale1, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale1), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale1), 0);

  hscale2 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale2);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale2, 296, 136);
  gtk_widget_set_size_request (hscale2, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale2), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale2), 0);

  hscale3 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale3);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale3, 296, 176);
  gtk_widget_set_size_request (hscale3, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale3), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale3), 0);

  hscale4 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale4);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale4, 296, 216);
  gtk_widget_set_size_request (hscale4, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale4), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale4), 0);

  hscale5 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale5);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale5, 296, 256);
  gtk_widget_set_size_request (hscale5, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale5), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale5), 0);

  hscale6 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale6);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale6, 296, 296);
  gtk_widget_set_size_request (hscale6, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale6), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale6), 0);

  hscale7 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale7);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale7, 296, 336);
  gtk_widget_set_size_request (hscale7, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale7), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale7), 0);

  hscale0 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale0);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale0, 296, 56);
  gtk_widget_set_size_request (hscale0, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale0), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale0), 0);

  hscale11 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 00, 1, 0, 0)));
  gtk_widget_show (hscale11);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale11, 624, 96);
  gtk_widget_set_size_request (hscale11, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale11), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale11), 0);

  hscale17 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale17);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale17, 624, 336);
  gtk_widget_set_size_request (hscale17, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale17), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale17), 0);

  hscale16 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale16);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale16, 624, 296);
  gtk_widget_set_size_request (hscale16, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale16), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale16), 0);

  hscale12 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale12);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale12, 624, 136);
  gtk_widget_set_size_request (hscale12, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale12), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale12), 0);

  hscale13 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale13);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale13, 624, 176);
  gtk_widget_set_size_request (hscale13, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale13), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale13), 0);

  hscale15 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale15);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale15, 624, 256);
  gtk_widget_set_size_request (hscale15, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale15), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale15), 0);

  hscale14 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale14);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale14, 624, 216);
  gtk_widget_set_size_request (hscale14, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale14), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale14), 0);

  hscale10 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -2000, 000, 1, 0, 0)));
  gtk_widget_show (hscale10);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale10, 624, 56);
  gtk_widget_set_size_request (hscale10, 152, 48);
  gtk_scale_set_value_pos (GTK_SCALE (hscale10), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale10), 0);

  button1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 872, 776);
  gtk_widget_set_size_request (button1, 80, 29);
  gtk_container_set_border_width (GTK_CONTAINER (button1), 1);


  button2 = gtk_button_new_from_stock ("gtk-revert-to-saved");
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 872, 746);
  gtk_widget_set_size_request (button2, 80, 29);
  gtk_container_set_border_width (GTK_CONTAINER (button2), 1);

  button3 = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 872, 716);
  gtk_widget_set_size_request (button3, 80, 29);
  gtk_container_set_border_width (GTK_CONTAINER (button3), 1);


  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 0, 384);
  gtk_widget_set_size_request (hseparator1, 1008, 16);


 label37 = gtk_label_new (("AutoSet"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed1), label37, 808, 24);
  gtk_widget_set_size_request (label37, 64, 24);

  checkbutton61 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton61);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton61, 808, 56);
  gtk_widget_set_size_request (checkbutton61, 119, 22);

  checkbutton62 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton62);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton62, 808, 96);
  gtk_widget_set_size_request (checkbutton62, 119, 22);

  checkbutton63 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton63);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton63, 808, 136);
  gtk_widget_set_size_request (checkbutton63, 119, 22);

  checkbutton64 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton64);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton64, 808, 176);
  gtk_widget_set_size_request (checkbutton64, 119, 22);

  checkbutton65 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton65);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton65, 808, 216);
  gtk_widget_set_size_request (checkbutton65, 119, 22);

  checkbutton66 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton66);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton66, 808, 256);
  gtk_widget_set_size_request (checkbutton66, 119, 22);

  checkbutton67 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton67);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton67, 808, 296);
  gtk_widget_set_size_request (checkbutton67, 119, 22);

  checkbutton68 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton68);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton68, 808, 336);
  gtk_widget_set_size_request (checkbutton68, 119, 22);


  label38 = gtk_label_new (("Coincidence level"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed1), label38, 504, 760);
  gtk_widget_set_size_request (label38, 120, 16);

  hscale33 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 8, 1, 0, 0)));
  gtk_widget_show (hscale33);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale33, 496, 776);
  gtk_widget_set_size_request (hscale33, 152, 30);
  gtk_scale_set_digits (GTK_SCALE (hscale33), 0);

  label39 = gtk_label_new (("Delay timeout ns\n(0: just prompt)"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed1), label39, 680, 680);
  gtk_widget_set_size_request (label39, 200, 32);

  hscale34 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 2000000, 5, 0, 0)));
  gtk_widget_show (hscale34);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale34, 712, 720);
  gtk_widget_set_size_request (hscale34, 136, 30);
  gtk_scale_set_value_pos (GTK_SCALE (hscale34), GTK_POS_BOTTOM);
  gtk_scale_set_digits (GTK_SCALE (hscale34), 0);

  label40 = gtk_label_new (("N samples over thr"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed1), label40, 712, 760);
  gtk_widget_set_size_request (label40, 136, 17);

  hscale35 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 10, 1, 0, 0)));
  gtk_widget_show (hscale35);
  gtk_fixed_put (GTK_FIXED (fixed1), hscale35, 712, 776);
  gtk_widget_set_size_request (hscale35, 136, 38);
  gtk_scale_set_digits (GTK_SCALE (hscale35), 0);


  label41 = gtk_label_new (("FRONT PANEL\nINPUT LEVEL\n\n\n"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed1), label41, 864, 552);
  gtk_widget_set_size_request (label41, 120, 33);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, ("N I M"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton11, 864, 592);
  gtk_widget_set_size_request (radiobutton11, 112, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, ("T T L"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton12, 864, 616);
  gtk_widget_set_size_request (radiobutton12, 112, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, label4, "label4");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2, label1, "label1");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, checkbutton13, "checkbutton13");
  GLADE_HOOKUP_OBJECT (window2, checkbutton0, "checkbutton0");
  GLADE_HOOKUP_OBJECT (window2, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window2, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window2, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window2, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window2, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (window2, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (window2, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (window2, checkbutton17, "checkbutton17");
  GLADE_HOOKUP_OBJECT (window2, checkbutton16, "checkbutton16");
  GLADE_HOOKUP_OBJECT (window2, checkbutton15, "checkbutton15");
  GLADE_HOOKUP_OBJECT (window2, checkbutton14, "checkbutton14");
  GLADE_HOOKUP_OBJECT (window2, checkbutton12, "checkbutton12");
  GLADE_HOOKUP_OBJECT (window2, checkbutton11, "checkbutton11");
  GLADE_HOOKUP_OBJECT (window2, checkbutton10, "checkbutton10");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");
  GLADE_HOOKUP_OBJECT (window2, checkbutton20, "checkbutton20");
  GLADE_HOOKUP_OBJECT (window2, checkbutton22, "checkbutton22");
  GLADE_HOOKUP_OBJECT (window2, checkbutton24, "checkbutton24");
  GLADE_HOOKUP_OBJECT (window2, checkbutton25, "checkbutton25");
  GLADE_HOOKUP_OBJECT (window2, checkbutton26, "checkbutton26");
  GLADE_HOOKUP_OBJECT (window2, checkbutton27, "checkbutton27");
  GLADE_HOOKUP_OBJECT (window2, checkbutton23, "checkbutton23");
  GLADE_HOOKUP_OBJECT (window2, checkbutton21, "checkbutton21");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");
  GLADE_HOOKUP_OBJECT (window2, label27, "label27");
  GLADE_HOOKUP_OBJECT (window2, label28, "label28");
  GLADE_HOOKUP_OBJECT (window2, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window2, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window2, checkbutton55, "checkbutton55");
  GLADE_HOOKUP_OBJECT (window2, checkbutton56, "checkbutton56");
  GLADE_HOOKUP_OBJECT (window2, checkbutton54, "checkbutton54");
  GLADE_HOOKUP_OBJECT (window2, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (window2, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (window2, label31, "label31");
  GLADE_HOOKUP_OBJECT (window2, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window2, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window2, label29, "label29");
  GLADE_HOOKUP_OBJECT (window2, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window2, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window2, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window2, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window2, label30, "label30");
  GLADE_HOOKUP_OBJECT (window2, label32, "label32");
  GLADE_HOOKUP_OBJECT (window2, label33, "label33");
  GLADE_HOOKUP_OBJECT (window2, hscale29, "hscale29");
  GLADE_HOOKUP_OBJECT (window2, hscale30, "hscale30");
  GLADE_HOOKUP_OBJECT (window2, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window2, label34, "label34");
  GLADE_HOOKUP_OBJECT (window2, checkbutton57, "checkbutton57");
  GLADE_HOOKUP_OBJECT (window2, checkbutton58, "checkbutton58");
  GLADE_HOOKUP_OBJECT (window2, checkbutton60, "checkbutton60");
  GLADE_HOOKUP_OBJECT (window2, checkbutton59, "checkbutton59");
  GLADE_HOOKUP_OBJECT (window2, hscale31, "hscale31");
  GLADE_HOOKUP_OBJECT (window2, label35, "label35");
  GLADE_HOOKUP_OBJECT (window2, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (window2, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (window2, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window2, hscale32, "hscale32");
  GLADE_HOOKUP_OBJECT (window2, label36, "label36");
  GLADE_HOOKUP_OBJECT (window2, hscale1, "hscale1");
  GLADE_HOOKUP_OBJECT (window2, hscale2, "hscale2");
  GLADE_HOOKUP_OBJECT (window2, hscale3, "hscale3");
  GLADE_HOOKUP_OBJECT (window2, hscale4, "hscale4");
  GLADE_HOOKUP_OBJECT (window2, hscale5, "hscale5");
  GLADE_HOOKUP_OBJECT (window2, hscale6, "hscale6");
  GLADE_HOOKUP_OBJECT (window2, hscale7, "hscale7");
  GLADE_HOOKUP_OBJECT (window2, hscale0, "hscale0");
  GLADE_HOOKUP_OBJECT (window2, hscale11, "hscale11");
  GLADE_HOOKUP_OBJECT (window2, hscale17, "hscale17");
  GLADE_HOOKUP_OBJECT (window2, hscale16, "hscale16");
  GLADE_HOOKUP_OBJECT (window2, hscale12, "hscale12");
  GLADE_HOOKUP_OBJECT (window2, hscale13, "hscale13");
  GLADE_HOOKUP_OBJECT (window2, hscale15, "hscale15");
  GLADE_HOOKUP_OBJECT (window2, hscale14, "hscale14");
  GLADE_HOOKUP_OBJECT (window2, hscale10, "hscale10");
  GLADE_HOOKUP_OBJECT (window2, hscale18, "hscale18");
  GLADE_HOOKUP_OBJECT (window2, button1, "button1");
  GLADE_HOOKUP_OBJECT (window2, button2, "button2");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, hseparator1, "hseparator1");

  GLADE_HOOKUP_OBJECT (window2, checkbutton61, "checkbutton61");
  GLADE_HOOKUP_OBJECT (window2, checkbutton62, "checkbutton62");
  GLADE_HOOKUP_OBJECT (window2, checkbutton63, "checkbutton63");
  GLADE_HOOKUP_OBJECT (window2, checkbutton64, "checkbutton64");
  GLADE_HOOKUP_OBJECT (window2, checkbutton65, "checkbutton65");
  GLADE_HOOKUP_OBJECT (window2, checkbutton66, "checkbutton66");
  GLADE_HOOKUP_OBJECT (window2, checkbutton67, "checkbutton67");
  GLADE_HOOKUP_OBJECT (window2, checkbutton68, "checkbutton68");


  GLADE_HOOKUP_OBJECT (window2, label38, "label38");
  GLADE_HOOKUP_OBJECT (window2, hscale33, "hscale33");
  GLADE_HOOKUP_OBJECT (window2, label39, "label39");
  GLADE_HOOKUP_OBJECT (window2, hscale34, "hscale34");
  GLADE_HOOKUP_OBJECT (window2, label40, "label40");
  GLADE_HOOKUP_OBJECT (window2, hscale35, "hscale35");



  GLADE_HOOKUP_OBJECT (window2, label41, "label41");
  GLADE_HOOKUP_OBJECT (window2, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (window2, radiobutton12, "radiobutton12");


  /*Defaul values goes here */

  gtk_toggle_button_set_active((GtkToggleButton*)radiobutton3,1); /* Register controlled mode */

  gtk_toggle_button_set_active((GtkToggleButton*)checkbutton54,0); /*enable interrupt on opt link*/ gtk_widget_set_sensitive(checkbutton54,0); 

  gtk_toggle_button_set_active((GtkToggleButton*)radiobutton7,1); /*Interrupt ack. RORA */
  gtk_widget_set_sensitive(radiobutton7,0);
  gtk_widget_set_sensitive(radiobutton8,0);
 
  gtk_range_set_value(GTK_RANGE(hscale32),0); /*interrupt level */
  gtk_widget_set_sensitive(hscale32,0);
   

  gtk_widget_set_sensitive(hscale30,0); /*interrupt event numbers */

  gtk_range_set_value(GTK_RANGE(hscale29),2);
  gtk_widget_set_sensitive(hscale29,0); /*MBLT event number */
 

  gtk_range_set_value(GTK_RANGE(hscale34),0); /*Coincidence level*/
  gtk_widget_set_sensitive( hscale34,0); /*Coincidence level*/



 gtk_toggle_button_set_active((GtkToggleButton*)radiobutton11,1); /*NIM */

  return window2;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed2;
  GtkWidget *button4;
  GtkWidget *button3;
  GtkWidget *button5;
  GtkWidget *button2;
  GtkWidget *button6;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), ("V1720 Control"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window1), fixed2);

  button4 = gtk_button_new_from_stock ("gtk-media-stop");
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 176, 16);
  gtk_widget_set_size_request (button4, 56, 32);

  button3 = gtk_button_new_from_stock ("gtk-media-play");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 112, 16);
  gtk_widget_set_size_request (button3, 64, 32);

  button5 = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 248, 16);
  gtk_widget_set_size_request (button5, 56, 32);

  button2 = gtk_button_new_with_mnemonic (("Configure"));
  gtk_widget_show(button2);
  gtk_fixed_put(GTK_FIXED (fixed2), button2, 24, 16);
  gtk_widget_set_size_request (button2, 80, 32);
 

  button6 = gtk_button_new_with_mnemonic (("Softw Trigg"));
  gtk_widget_show(button6);
  gtk_fixed_put(GTK_FIXED (fixed2), button6, 320, 16);
  gtk_widget_set_size_request (button6, 80, 32);


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");


  return window1;
}

